name: StartUREngines
favicon: null
layout_spectrum: 0.990748340729624
typography_spectrum: 0.8146257668267936
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.6073406776413321
  lightness: 0.9165143661666662
  saturation: 0.7890405878424644
  rhythmicContrast: 0.27785052452236414
purpose: []
